Repository AY2425S2-CS2103T-F13-3/tp, pull requests merged in 2025-04, with the labels that each got.

#114 Update DeleteSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: type.Task

#151 Fix [Add] bugs
  src/main/java/hirehive/address/logic/Messages.java
  src/main/java/hirehive/address/logic/commands/AddCommand.java
  src/main/java/hirehive/address/logic/commands/EditCommand.java
  src/main/java/hirehive/address/model/person/Name.java
Labels: type.Bug, alpha-bug

#281 Fix Add Command part of UG
  docs/UserGuide.md
Labels: type.Bug, priority.High
